name: calory_tool
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  #~ Network
  dio: ^5.8.0+1

  #~ Cache
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  #~ State Management
  provider: ^6.1.2
  mobx: ^2.5.0
  flutter_mobx: ^2.3.0

  #~ Dependency Injection
  get_it: ^8.0.3

  #~ Localization
  easy_localization: ^3.0.7+1

  #~ Routing
  auto_route: ^9.3.0+1

  #~ Utils
  share_plus: ^10.1.4

  penta_core:
    git:
      url: https://github.com/ANILSRGT/flutter_penta_core.git
      ref: v1.1.3

dependency_overrides:
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

  build_runner: ^2.4.15
  hive_generator: ^2.0.1
  mobx_codegen: ^2.7.0
  auto_route_generator: ^9.0.0

flutter:
  uses-material-design: true
